services:
  app:
    build: .
    container_name: tornado-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: tornado_db
      DB_USER: root
      DB_PASS: password
    volumes:
      - .:/var/www

  db:
    image: mysql:8.0
    container_name: tornado-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tornado_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
